swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: go-pets-ega5bq4rma-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://go-pets-ega5bq4rma-uc.a.run.app
  protocol: h2
paths:
  /about:
    get:
      summary: Says what it is
      operationId: about
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /add:
    post:
      summary: Adds new pet
      operationId: addPet
      parameters:
        - in: body
          name: pet
          description: pet
          schema:
            type: object
            required:
              - caption
              - email
              - owner
              - petname
            properties:
              caption:
                type: string
              email:
                type: string
              owner:
                type: string
              petname:
                type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  